# Generated by Django 5.2 on 2025-08-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Users'), ('jobseeker', 'Jobseeker'), ('employer', 'Employer'), ('superadmin', 'Super Admin')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=2025, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('jobseeker', 'Jobseekers'), ('employer', 'Employers'), ('specific', 'Specific Users')], default='all', max_length=20)),
                ('recipients', models.ManyToManyField(blank=True, related_name='manual_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
