# Generated by Django 5.2 on 2025-05-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
