# Generated by Django 5.2 on 2025-05-07 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_employerprofile_license_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='license_document',
            new_name='license_file',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='is_verified',
            new_name='license_verified',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('direct', 'Direct Hire (Individual/Company)'), ('local_agency', 'Local Recruitment Agency'), ('overseas_agency', 'Overseas Recruitment Agency')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
