# Generated by Django 5.2 on 2025-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_rename_license_document_employerprofile_license_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='official_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
