# Generated by Django 5.2 on 2025-06-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_alter_employerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(max_length=50),
        ),
    ]
