# Generated by Django 5.2 on 2025-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_alter_employerprofile_employer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
