# Generated by Django 5.2 on 2025-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_employerprofile_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('agency', 'Agency'), ('ngo', 'NGO'), ('government', 'Government')], max_length=50),
        ),
    ]
