# Generated by Django 5.2 on 2025-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_employee_added_by_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
