# Generated by Django 5.2 on 2025-05-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
