# Generated by Django 5.2 on 2025-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
