# Generated by Django 5.2 on 2025-05-05 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='default_location', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
