# Generated by Django 5.2 on 2025-05-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_city_job_country_job_english_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='perks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
