# Generated by Django 5.2 on 2025-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_employer_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], max_length=20),
        ),
    ]
