# Generated by Django 5.2 on 2025-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
