# Generated by Django 5.2 on 2025-06-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_alter_employerprofile_employer_type'),
        ('jobs', '0011_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employerprofile'),
        ),
    ]
