# Generated by Django 5.2 on 2025-06-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_alter_employerprofile_employer_type'),
        ('jobs', '0012_alter_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employerprofile'),
        ),
    ]
