# Generated by Django 5.2 on 2025-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_openai', models.BooleanField(default=False)),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('active_models', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Setting',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
