# Generated by Django 5.2 on 2025-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_alter_jobseeker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
