# Generated by Django 5.2 on 2025-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0003_jobseeker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
