# Generated by Django 5.2 on 2025-04-26 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(choices=[('direct', 'Direct Hire'), ('agency_local', 'Local Agency'), ('agency_overseas', 'Overseas Agency')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
