# Generated by Django 5.2 on 2025-05-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer'), ('superadmin', 'Super Admin')], default='jobseeker', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='bir_2303',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default=2025, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='official_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
