# Generated by Django 5.2 on 2025-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_ai_access',
            field=models.BooleanField(default=False),
        ),
    ]
