# Generated by Django 5.2 on 2025-06-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_has_ai_access'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
