# Generated by Django 5.2 on 2025-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10),
        ),
    ]
