# Generated by Django 5.2 on 2025-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ai_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
