# Generated by Django 5.2 on 2025-06-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_ai_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='employer',
            new_name='user',
        ),
    ]
