# Generated by Django 5.2 on 2025-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_post_limit', models.IntegerField(default=1)),
                ('resume_access_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
